export interface Project {
  id?:any;
  data?:any;
  success?:boolean;
  message?:string;
  name:string,
  description:string,
  category:string,
  project_image:string,
  client:string,
  contractor:string,
  contractor_contacts:string,
  facilitator_name:string,
  facilitator_contacts:string,
  ministry:string,
  total_duration:string,
  start_date:string,
  end_date:string,
  status:string;
}
